
BoxLayout:
    orientation : "vertical"

    Label:
        id : connection_status
        text:"connection status : searching..."
        size_hint : (1, .3)
        padding : 0, 0, 0, 10
        color : 1, .1, .0, 1
    Label:
        text : "enter username"
        size_hint : (0.5, 0.1)

    TextInput:
        id : username_input
    Button:
        text : "make user"
        on_press : app.make_user(username_input.text)
